"""证据驱动工程运行状态基础。"""

from src.core.engineering.classifier import TaskIntentClassifier
from src.core.engineering.audit import CompletionAuditor, MutationRiskEscalator
from src.core.engineering.evidence import ToolEvidenceRecorder, file_mutation_metadata
from src.core.engineering.execution_depth import ExecutionDepthResolver
from src.core.engineering.models import (
    Evidence,
    ExecutionBudget,
    ExecutionDepthDecision,
    CompletionAudit,
    Hypothesis,
    ObservedMutation,
    ProjectReconnaissance,
    RequirementCheck,
    RunJournal,
    TaskExecutionPolicy,
    TaskIntent,
    VerificationGate,
    WorkPlan,
    WorkPlanStep,
)
from src.core.engineering.verifier import VerificationTracker
from src.core.engineering.journal import RunJournalStore
from src.core.engineering.report import (
    DeliveryItem,
    DeliveryReport,
    DeliveryReportBuilder,
    load_today_journals,
)
from src.core.engineering.replay import StabilityReplayOutcome, StabilityReplayRunner
from src.core.engineering.recovery import (
    RecoveryConfirmationRequired,
    RecoveryState,
    SessionRecoveryManager,
)
from src.core.engineering.benchmark import (
    BenchmarkAggregate,
    BenchmarkExecution,
    BenchmarkFileExpectation,
    BenchmarkOfflineFixture,
    BenchmarkReport,
    BenchmarkRunResult,
    BenchmarkStability,
    BenchmarkStrategy,
    BenchmarkStrategyProfile,
    BenchmarkSuite,
    BenchmarkTask,
    BenchmarkVerificationContract,
    EngineeringBenchmarkHarness,
    FixtureBenchmarkStrategy,
    LiveBenchmarkAuthorization,
    LiveBenchmarkSpendGuard,
    MaoLiveBenchmarkStrategy,
    load_benchmark_suite,
    write_benchmark_report,
)

__all__ = [
    "Evidence",
    "ExecutionBudget",
    "ExecutionDepthDecision",
    "ExecutionDepthResolver",
    "CompletionAudit",
    "CompletionAuditor",
    "MutationRiskEscalator",
    "Hypothesis",
    "ObservedMutation",
    "ProjectReconnaissance",
    "RequirementCheck",
    "RunJournal",
    "RunJournalStore",
    "DeliveryItem",
    "DeliveryReport",
    "DeliveryReportBuilder",
    "load_today_journals",
    "StabilityReplayOutcome",
    "StabilityReplayRunner",
    "RecoveryConfirmationRequired",
    "RecoveryState",
    "SessionRecoveryManager",
    "TaskExecutionPolicy",
    "TaskIntent",
    "TaskIntentClassifier",
    "ToolEvidenceRecorder",
    "file_mutation_metadata",
    "VerificationTracker",
    "VerificationGate",
    "WorkPlan",
    "WorkPlanStep",
    "BenchmarkAggregate",
    "BenchmarkExecution",
    "BenchmarkFileExpectation",
    "BenchmarkOfflineFixture",
    "BenchmarkReport",
    "BenchmarkRunResult",
    "BenchmarkStability",
    "BenchmarkStrategy",
    "BenchmarkStrategyProfile",
    "BenchmarkSuite",
    "BenchmarkTask",
    "BenchmarkVerificationContract",
    "EngineeringBenchmarkHarness",
    "FixtureBenchmarkStrategy",
    "LiveBenchmarkAuthorization",
    "LiveBenchmarkSpendGuard",
    "MaoLiveBenchmarkStrategy",
    "load_benchmark_suite",
    "write_benchmark_report",
]
